// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xctmsinerchsezyihwlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdG1zaW5lcmNoc2V6eWlod2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDQzMTUsImV4cCI6MjA2ODE4MDMxNX0.qtiVo9YYerO1NXoBigX5zqK3FjxWulB-iuQKw1Bib0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});